version: "3.8"

services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  party-organizer:
    build: .
    container_name: party-organizer
    depends_on:
      - kafka
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: r2dbc:postgresql://host.docker.internal:5432/party_organizer_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      WHATSAPP_API_URL: https://graph.facebook.com
      WHATSAPP_TOKEN: SEU_TOKEN_DO_WHATSAPP
      WHATSAPP_PHONE_NUMBER_ID: SEU_PHONE_NUMBER_ID
